name: Build Docker Image for Web

on:
  push:
    paths:
      - 'apps/web/**'
  pull_request:
    paths:
      - 'apps/web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -f ./apps/api/Dockerfile .

